### ISSUE TITLE
How to install/build/integrate la_wall_MIRTK with MIRTK

### ISSUE THREAD

**Issue by ilsemeijer99** [drkarim/la_wall_MIRTK#2]
I installed MIRTK with cmake on my windows laptop. However I do not understand how to integrate the evaluate_la_wall functions with my preinstalled version of MIRTK. Right now I receive the error when trying to build la_wall_MIRTK with cmake, that the #include lines in evaluate_la_wall do not recognize the path to my mirtk installation (which is located in Program Files).

**Comment by drkarim** [comment]
Let me see if I can help, it's been a while working with this mirtk, but I will try. 

Usually in cmake you have to specify the path of the mirtk installation. You need to compile MIRTK from source in order to make this work. Can you confirm you have done that? 

Under this repo's config folder, in the [FindMIRTK.cmake file](https://github.com/drkarim/la_wall_MIRTK/blob/master/config/FindMIRTK.cmake), the `mirtk_root` variable is set in lines 155, but the path is fetched from the user specifying it in CMake.  

` # Use MIRTK_ROOT as cache entry
  set (MIRTK_ROOT "${MIRTK_ROOT}" CACHE PATH "Installation prefix/root directory of MIRTK.")`

**Comment by ilsemeijer99** [comment]
Thank you for your response. In the meantime I solved it. I did compile mirtk from source successfully. I solved it by only building mirtk and la_wall_mirtk (not installing with cmake), adding the .exe files of the la_wall_mirtk build to the mirtk build folder and adding mirtk to my path. Not sure if some of these steps could have been avoided, but it works now! thank you :)

**Comment by drkarim** [comment]
Glad to hear that you made it work, and thanks for posting your solution. All the best!
